# -*- coding: utf-8 -*-
"""
nms_lookup.py — паспорт детали NMS по ObjectID одной командой. Всё 1:1 из данных игры.

Использование:
    python nms_lookup.py TELEPORTER
    python nms_lookup.py _WALLB --style Timber
    python nms_lookup.py W_WALL --json
    python nms_lookup.py S_CONTAINER0 --brief     (без разбора сцены/материалов)

Что делает (цепочка сборки детали, Правило 31 — только игровые данные):
  1. objectstable  (PRECACHE_FULL!)  — паспорт GcBaseBuildingEntry: стиль, PlacementScene,
     SinglePartID, группы меню, палитры, флаги Can*/Buildable*, композиты, семьи.
  2. partstable    (PRECACHE_FULL!)  — StyleModels: стиль -> сцена (.SCENE.MBIN).
  3. legacybasebuildingtable (PRECACHE_FULL) — легаси-группа, если есть.
  4. Сцена (SCENES_PARTS_NEW) — GEOMETRY, LOD, MESH-узлы + материалы, LOCATOR/SnapPoint,
     REFERENCE (составная!), COLLISION.
  5. Материалы (MBINCompiler\\MATERIALS полные имена -> META_NEW -> NEW_EXTRACT_2026):
     Class, флаги _F, gMaterialColourVec4, сэмплеры (diffuse/masks/normal/cmask + sRGB).
  6. Геометрия — поиск по ПОЛНОМУ пути во всех дампах {UNPACK_ALL_MESHES, FULL, GEO2,
     MESHCOMMON_FULL, NEW_EXTRACT_2026}; лучший кандидат = самый большой .geometry.data.MXML.
  7. Хулл MagicData (autogeneratedpartsdata, PRECACHE_FULL) — мировой bbox эталона.
  8. Иконка (Правило 18): part_icons_official.json + ИКОНКИ_PNG\\<ID>.png.
  9. Состояние в проекте NMS_BuilderApp: nms_parts_db (ModelPath), part_slots (слоты),
     MeshSrc\\*.obj, GameMeshes\\*.uasset, verified_meshes.

ВАЖНО: таблицы ТОЛЬКО из PRECACHE_FULL\\metadata\\reality\\tables — корневые копии в
MBINCompiler\\ старые и дают НЕВЕРНЫЙ меш (инцидент TELEPORTER 01.07.2026).
"""
import argparse
import json
import os
import re
import sys
import xml.etree.ElementTree as ET

try:
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
except Exception:
    pass

# ------------------------------------------------------------------ пути
MB = r"C:\Users\User\Desktop\MBINCompiler"
EX = r"C:\Users\User\Desktop\NMS_EXTRACT"
PROJ = r"C:\Users\User\Documents\Unreal Projects\NMS_BuilderApp"

TABLES = os.path.join(MB, "PRECACHE_FULL", "metadata", "reality", "tables")
OBJECTSTABLE = os.path.join(TABLES, "basebuildingobjectstable.MXML")
PARTSTABLE = os.path.join(TABLES, "basebuildingpartstable.MXML")
LEGACYTABLE = os.path.join(TABLES, "legacybasebuildingtable.MXML")
AUTOGEN = os.path.join(TABLES, "basebuildingautogeneratedpartsdata.MXML")

SCENE_DIRS = [os.path.join(EX, "SCENES_PARTS_NEW"),
              os.path.join(MB, "NEW_EXTRACT_2026")]
GEO_DIRS = [os.path.join(MB, "UNPACK_ALL_MESHES"),
            os.path.join(MB, "FULL"),
            os.path.join(MB, "GEO2"),
            os.path.join(MB, "MESHCOMMON_FULL"),
            os.path.join(MB, "NEW_EXTRACT_2026")]
MAT_DIRS_FULLNAME = [os.path.join(MB, "MATERIALS"),
                     os.path.join(MB, "NEW_EXTRACT_2026")]
MAT_DIRS_SHORTNAME = [os.path.join(EX, "MATERIALS_META_NEW")]

ICON_MAP = os.path.join(EX, "6_LOGIC_NOTES", "part_icons_official.json")
ICON_PNG_DIR = os.path.join(EX, "ИКОНКИ_PNG")

PARTS_DB = os.path.join(PROJ, "Content", "nms_parts_db.json")
PART_SLOTS = os.path.join(PROJ, "Content", "NMSData", "part_slots.json")
PART_TEXTURES = os.path.join(PROJ, "Content", "NMSData", "part_textures.json")
VERIFIED_MESHES = os.path.join(PROJ, "Content", "NMSData", "verified_meshes.json")
MESHSRC = os.path.join(PROJ, "MeshSrc")
GAMEMESHES = os.path.join(PROJ, "Content", "NMSBaseBuilder", "GameMeshes")

# ------------------------------------------------------------------ утилиты

def prop_val(text, name, default=""):
    """Первое <Property name="NAME" value="..."/> в куске текста."""
    m = re.search(r'<Property name="%s" value="([^"]*)"' % re.escape(name), text)
    return m.group(1) if m else default


def prop_vals(text, name):
    return re.findall(r'<Property name="%s" value="([^"]*)"' % re.escape(name), text)


def norm_key(game_path):
    """MODELS\\A\\B\\C.SCENE.MBIN -> models__a__b__c (без расширения)."""
    p = game_path.replace("\\", "/").lower()
    p = re.sub(r"\.(scene|geometry|material)\.mbin$", "", p)
    p = re.sub(r"\.(scene|geometry|material)$", "", p)
    return p.strip("/").replace("/", "__")


def suffix_match(full_key, fname_base):
    """Совпадение на границе '__': короткое имя = хвост полного пути."""
    if full_key == fname_base:
        return True
    if full_key.endswith("__" + fname_base):
        return True
    if fname_base.endswith("__" + full_key):
        return True
    return False


_dir_cache = {}

def list_dir(d, recursive=False):
    if d in _dir_cache:
        return _dir_cache[d]
    out = []
    if os.path.isdir(d):
        if recursive:
            for root, _dirs, files in os.walk(d):
                for f in files:
                    out.append(os.path.join(root, f))
        else:
            out = [os.path.join(d, f) for f in os.listdir(d)]
    _dir_cache[d] = out
    return out


def find_decoded(game_path, dirs, ext, with_quality=False):
    """Ищет расшифрованный файл (.scene.MXML / .geometry.data.MXML / .material.MXML)
    по игровому пути во всех папках; сверка по ПОЛНОМУ пути на границе '__'.
    Для папок с реальной структурой (MESHCOMMON_FULL) ключ = относительный путь,
    а не голое имя — иначе чужие одноимённые меши (teleporter!) дают ложный матч.
    quality: 'exact' = полный путь совпал, 'suffix' = совпал только хвост имени."""
    key = norm_key(game_path)
    hits = []
    for d in dirs:
        recursive = d.endswith("MESHCOMMON_FULL")
        for f in list_dir(d, recursive=recursive):
            base = os.path.basename(f)
            if not base.endswith(ext):
                continue
            if recursive:
                rel = os.path.relpath(f, d)
                fb = rel[: -len(ext)].lower().replace("\\", "__").replace("/", "__")
            else:
                fb = base[: -len(ext)].lower()
            if not suffix_match(key, fb):
                continue
            exact = (fb == key or fb.endswith("__" + key))
            hits.append((f, "exact" if exact else "suffix"))
    if with_quality:
        return hits
    return [f for f, _q in hits]


def find_table_entry(path, id_regex, open_prefix):
    """Стриминг по таблице: копим текущую запись (открытие на open_prefix),
    возвращаем первую запись, где встретился id_regex."""
    rx = re.compile(id_regex)
    close_line = open_prefix.split("<")[0] + "</Property>"
    entry = []
    inside = False
    hit = False
    with open(path, "r", encoding="utf-8", errors="replace") as fh:
        for line in fh:
            ls = line.rstrip("\n")
            if ls.startswith(open_prefix):
                entry = [ls]
                inside = True
                hit = bool(rx.search(ls))
                continue
            if inside:
                entry.append(ls)
                if not hit and rx.search(ls):
                    hit = True
                if ls == close_line:
                    if hit:
                        return "\n".join(entry)
                    inside = False
                    entry = []
    return None


def find_table_entries(path, id_regex, open_prefix, limit=8):
    """Как выше, но все записи (например хуллы по всем стилям)."""
    rx = re.compile(id_regex)
    close_line = open_prefix.split("<")[0] + "</Property>"
    out = []
    entry = []
    inside = False
    hit = False
    with open(path, "r", encoding="utf-8", errors="replace") as fh:
        for line in fh:
            ls = line.rstrip("\n")
            if ls.startswith(open_prefix):
                entry = [ls]
                inside = True
                hit = bool(rx.search(ls))
                continue
            if inside:
                entry.append(ls)
                if not hit and rx.search(ls):
                    hit = True
                if ls == close_line:
                    if hit:
                        out.append("\n".join(entry))
                        if len(out) >= limit:
                            return out
                    inside = False
                    entry = []
    return out

# ------------------------------------------------------------------ разборы


def parse_objectstable(oid):
    entry = find_table_entry(
        OBJECTSTABLE, r'_id="%s"' % re.escape(oid),
        '\t\t<Property name="Objects"')
    if not entry:
        return None
    groups = re.findall(
        r'<Property name="Group" value="([^"]*)" />\s*\n\s*'
        r'<Property name="SubGroupName" value="([^"]*)"', entry)
    style_m = re.search(
        r'name="Style" value="GcBaseBuildingPartStyle">\s*\n\s*'
        r'<Property name="Style" value="([^"]*)"', entry)
    comp_block = re.search(
        r'<Property name="CompositePartObjectIDs">(.*?)^\t{3}</Property>',
        entry, re.S | re.M)
    composites = prop_vals(comp_block.group(1), "CompositePartObjectIDs") if comp_block else []
    fam_block = re.search(
        r'<Property name="FamilyIDs">(.*?)^\t{3}</Property>', entry, re.S | re.M)
    families = prop_vals(fam_block.group(1), "FamilyIDs") if fam_block else []
    return {
        "ID": prop_val(entry, "ID"),
        "Style": style_m.group(1) if style_m else "",
        "PlacementScene": prop_val(entry, "Filename"),
        "SinglePartID": prop_val(entry, "SinglePartID"),
        "IsPlaceable": prop_val(entry, "IsPlaceable"),
        "ShowInBuildMenu": prop_val(entry, "ShowInBuildMenu"),
        "Groups": ["%s / %s" % g for g in groups],
        "ColourPaletteGroupId": prop_val(entry, "ColourPaletteGroupId"),
        "MaterialGroupId": prop_val(entry, "MaterialGroupId"),
        "CanChangeColour": prop_val(entry, "CanChangeColour"),
        "CanChangeMaterial": prop_val(entry, "CanChangeMaterial"),
        "CanScale": prop_val(entry, "CanScale"),
        "CanRotate3D": prop_val(entry, "CanRotate3D"),
        "SnapRotateBlocked": prop_val(entry, "SnapRotateBlocked"),
        "Buildable": {k: prop_val(entry, k) for k in (
            "BuildableOnPlanetBase", "BuildableOnSpaceBase", "BuildableOnFreighter",
            "BuildableUnderwater", "BuildableOnPlanet")},
        "CompositePartObjectIDs": composites,
        "FamilyIDs": families,
        "HasLinkGridData": 'name="LinkGridData"' in entry,
    }


def parse_partstable(pid):
    entry = find_table_entry(
        PARTSTABLE, r'<Property name="ID" value="%s" />' % re.escape(pid),
        '\t\t<Property name="Table"')
    if entry is None:
        # формат открытия записи мог отличаться — пробуем универсально по любому 2-таб открытию
        entry = find_table_entry(
            PARTSTABLE, r'<Property name="ID" value="%s" />' % re.escape(pid),
            '\t\t<Property ')
    if not entry:
        return None
    styles = re.findall(
        r'<Property name="Style" value="([^"]*)" />\s*\n\s*</Property>\s*\n\s*'
        r'<Property name="Model" value="TkModelResource">\s*\n\s*'
        r'<Property name="Filename" value="([^"]*)"', entry)
    return {"ID": pid, "StyleModels": [{"Style": s, "Scene": f} for s, f in styles]}


def parse_legacy(oid):
    if not os.path.isfile(LEGACYTABLE):
        return None
    entry = find_table_entry(
        LEGACYTABLE, r'value="%s"' % re.escape(oid), '\t\t<Property ')
    return {"found": bool(entry)} if entry else None


def hull_bbox(pid, style=None):
    """MagicData-хуллы (мировой эталон): все стили, bbox каждого."""
    entries = find_table_entries(
        AUTOGEN, r'<Property name="PartID" value="%s" />' % re.escape(pid),
        '\t\t<Property name="PartsData"')
    out = []
    for e in entries:
        st = ""
        m = re.search(r'name="Style" value="GcBaseBuildingPartStyle">\s*\n\s*'
                      r'<Property name="Style" value="([^"]*)"', e)
        if m:
            st = m.group(1)
        xs = [float(v) for v in prop_vals(e, "X")]
        ys = [float(v) for v in prop_vals(e, "Y")]
        zs = [float(v) for v in prop_vals(e, "Z")]
        if not xs:
            continue
        out.append({
            "Style": st,
            "min": [min(xs), min(ys), min(zs)],
            "max": [max(xs), max(ys), max(zs)],
            "size": [max(xs) - min(xs), max(ys) - min(ys), max(zs) - min(zs)],
            "nverts": len(xs),
        })
    if style:
        pref = [h for h in out if h["Style"].lower() == style.lower()]
        if pref:
            return pref + [h for h in out if h not in pref]
    return out

# --------- сцена (ElementTree) ---------


def et_props(el):
    """Дочерние <Property> по name."""
    d = {}
    for c in el:
        d.setdefault(c.get("name"), []).append(c)
    return d


def node_info(el):
    p = et_props(el)
    name = p.get("Name", [None])[0]
    typ = p.get("Type", [None])[0]
    info = {
        "Name": name.get("value") if name is not None else "",
        "Type": typ.get("value") if typ is not None else "",
        "Attrs": {},
        "Transform": {},
        "Children": [],
    }
    tr = p.get("Transform", [None])[0]
    if tr is not None:
        for c in tr:
            info["Transform"][c.get("name")] = c.get("value")
    attrs = p.get("Attributes", [None])[0]
    if attrs is not None:
        for a in attrs:
            ap = et_props(a)
            an = ap.get("Name", [None])[0]
            av = ap.get("Value", [None])[0]
            if an is not None and av is not None:
                info["Attrs"][an.get("value")] = av.get("value")
    ch = p.get("Children", [None])[0]
    if ch is not None:
        for c in ch:
            info["Children"].append(node_info(c))
    return info


def walk_nodes(node, out=None):
    if out is None:
        out = []
    out.append(node)
    for c in node["Children"]:
        walk_nodes(c, out)
    return out


def parse_scene(scene_file):
    tree = ET.parse(scene_file)
    root_prop = tree.getroot()  # <Data>
    root = node_info(root_prop)
    nodes = walk_nodes(root)
    meshes, locators, refs, colls = [], [], [], []
    for n in nodes:
        t = n["Type"]
        if t == "MESH":
            lod = n["Attrs"].get("LODLEVEL", "")
            meshes.append({
                "Name": n["Name"],
                "MATERIAL": n["Attrs"].get("MATERIAL", ""),
                "LODLEVEL": lod,
            })
        elif t == "LOCATOR":
            tr = n["Transform"]
            locators.append({
                "Name": n["Name"],
                "pos": [tr.get("TransX"), tr.get("TransY"), tr.get("TransZ")],
                "rotY": tr.get("RotY"),
            })
        elif t == "REFERENCE":
            refs.append({"Name": n["Name"],
                         "SCENEGRAPH": n["Attrs"].get("SCENEGRAPH", "")})
        elif t == "COLLISION":
            colls.append({"Name": n["Name"],
                          "TYPE": n["Attrs"].get("TYPE", "")})
    return {
        "file": scene_file,
        "GEOMETRY": root["Attrs"].get("GEOMETRY", ""),
        "NUMLODS": root["Attrs"].get("NUMLODS", ""),
        "meshes": meshes,
        "locators": locators,
        "references": refs,
        "collisions": colls,
    }


# ---------------------------------------------------------------- эмуляция шейдера
# Числовой «портрет пикселя» материала — что убершейдер игры сделает с этим материалом.
# Формулы 1:1 из проверенной заметки 6_LOGIC_NOTES\ИССЛЕДОВАНИЕ_ДЕТАЛИ_2026-07\10_ATLAS_KRASKA
# (frag 22517998153629701, адверсарно сверено на 4337 материалах). Точнее симулятора
# NMS_АТЛАС_ИСТИНА: несёт Subsurface (masks.A·Params.y) и правку применения AO (лерп ambient).

# бит gDynamicFlags.x -> активная ветка. ПРОВЕРЕНО ПРЯМО ПО ИГРОВОМУ ШЕЙДЕРУ
# SHADERS_FULL\...\ubershader_frag_lit_defer_22517998153629701.glsl (декомпиляция .spv игры):
#   бит 1 → _1940 (стр.253), 2 → _1943 (269), 4 → _1947 (285), 8 → _1949 (301),
#   16 → _1942/subsurface (262), 256 → _1930/покраска (214), 8192 → _1948/glow (292).
DYNBITS = {
    1:    "Roughness = (1−masks.R)·Params.x  (иначе 1·Params.x)  [_1940]",
    2:    "Metallic = masks.G  (иначе Params.z)  [_1943]",
    4:    "spec/scatter G-буфер.w = masks.G·Params.w  (иначе 0)  [_1947]",
    8:    "Glow-маска = masks.B  (иначе 1)  [_1949]",
    16:   "Subsurface из masks.A  (иначе 1·Params.y)  [_1942]",
    64:   "AO = gOcclusionMap.G",
    256:  "★ покраска: zone = 4−int(cmask.R·4+0.5), albedo·=свотч[zone]  [_1930]",
    2048: "AO ограничен вершинным цветом.w (min)",
    8192: "Glow-сила = Params2.x  [_1948]",
}


def _f(vals, i, default=0.0):
    try:
        return float(vals[i])
    except (TypeError, ValueError, IndexError):
        return default


def emulate_shader(flags, uniforms):
    """Возвращает dict: активные биты + формулы Roughness/Metallic/Glow/Subsurface/AO/zone
    с подставленными числами материала. Всё 1:1 из GLSL (см. заметку 10)."""
    fl = set(flags or [])
    dynx = 0
    dv = uniforms.get("gDynamicFlags")
    if dv:
        try:
            dynx = int(float(dv[0])) if dv[0] not in (None, "") else 0
        except (TypeError, ValueError):
            dynx = 0
    P = uniforms.get("gMaterialParamsVec4") or []
    P2 = uniforms.get("gMaterialParams2Vec4") or []
    px, py, pz = _f(P, 0, 0.9), _f(P, 1, 0.5), _f(P, 2, 0.0)
    out = {
        "dyn_x": dynx,
        "active_bits": [(b, d) for b, d in sorted(DYNBITS.items()) if dynx & b],
        "roughness": ("clamp((1−masks.R)·%.2f)" % px) if (dynx & 1) else ("clamp(1·%.2f)=%.2f" % (px, min(px, 1.0))),
        "metallic": "masks.G" if (dynx & 2) else ("Params.z=%.2f" % pz),
    }
    if dynx & 8192:
        gmask = "masks.B" if (dynx & 8) else "1"
        out["glow"] = "clamp(%s·Params2.x=%.2f, 0..4)" % (gmask, _f(P2, 0, 0.0))
    else:
        out["glow"] = "0 (выключено)"
    # Subsurface — наша ключевая находка: masks.A НЕ AO, а подповерхностное свечение.
    # Гейт — ТОЧНЫЙ игровой бит 16 (не «есть _F25»): shader _1942 = (dyn&16?masks.A:1)·Params.y
    out["subsurface"] = ("masks.A·Params.y=%.2f" % py) if (dynx & 16) else ("1·Params.y=%.2f (masks.A-ветка выкл)" % py)
    out["ao"] = "gOcclusionMap.G" + ("  (min с вершинным.w)" if (dynx & 2048) else "") if (dynx & 64) else "1.0 (нет AO-карты)"
    if dynx & 256:
        out["paint"] = "zone = 4−int(cmask.R·4+0.5); zone<4 → albedo·=свотч палитры[zone] (без своей cmask: R=126 → зона 2 целиком)"
    else:
        out["paint"] = "не красится (бит 256 выкл)"
    out["is_multitexture"] = "_F55_MULTITEXTURE" in fl
    out["is_glass"] = "_F30_REFRACTION" in fl
    out["is_unlit"] = "_F07_UNLIT" in fl
    out["uv2"] = ("_F16_DIFFUSE2MAP" in fl) or ("_F42_DETAIL_NORMAL" in fl)
    return out


def parse_material(mat_path_game):
    """Материал по игровому пути: полное имя (MATERIALS/NEW_EXTRACT) ->
    короткое имя (META_NEW, с предупреждением о коллизиях)."""
    hits = find_decoded(mat_path_game, MAT_DIRS_FULLNAME, ".material.MXML")
    approx = False
    if not hits:
        short = norm_key(mat_path_game).split("__")[-1]
        for d in MAT_DIRS_SHORTNAME:
            for f in list_dir(d):
                b = os.path.basename(f)
                if b.lower() == short + ".material.mxml":
                    hits.append(f)
                    approx = True
    if not hits:
        return {"game_path": mat_path_game, "decoded": None}
    f = hits[0]
    try:
        tree = ET.parse(f)
    except ET.ParseError:
        return {"game_path": mat_path_game, "decoded": f, "error": "parse"}
    txt_flags, samplers = [], []
    mclass = ""
    colour = None
    uniforms = {}   # имя юниформы -> [X,Y,Z,W] (Float + UInt: Params/Params2/DynamicFlags)
    root = tree.getroot()

    def _xyzw(el):
        # X/Y/Z/W лежат под под-свойством "Values" (не прямые дети юниформы)
        p = et_props(el)
        holder = p["Values"][0] if "Values" in p else el
        vp = et_props(holder)
        return [vp[k][0].get("value") if k in vp else None for k in ("X", "Y", "Z", "W")]

    def rec(el):
        nonlocal mclass, colour
        name = el.get("name")
        val = el.get("value") or ""
        if name == "MaterialFlag":
            txt_flags.append(el.get("value"))
        elif name == "MaterialClass":
            mclass = el.get("value")
        elif name == "Samplers" and val == "TkMaterialSampler":
            p = et_props(el)
            samplers.append({
                "Name": p["Name"][0].get("value") if "Name" in p else "",
                "Map": p["Map"][0].get("value") if "Map" in p else "",
                "IsSRGB": p["IsSRGB"][0].get("value") if "IsSRGB" in p else "",
            })
        elif name in ("Uniforms_Float", "Uniforms_UInt") and val.startswith("TkMaterialUniform"):
            p = et_props(el)
            un = p["Name"][0].get("value") if "Name" in p else ""
            if un:
                uniforms[un] = _xyzw(el)
                if un == "gMaterialColourVec4":
                    colour = uniforms[un]
        for c in el:
            rec(c)

    rec(root)
    return {
        "game_path": mat_path_game,
        "decoded": f,
        "approx_by_name": approx,
        "Class": mclass,
        "Flags": txt_flags,
        "gMaterialColourVec4": colour,
        "Uniforms": uniforms,
        "Shader": emulate_shader(txt_flags, uniforms),
        "Samplers": samplers,
    }


def find_geometry(geo_path_game):
    hits = find_decoded(geo_path_game, GEO_DIRS, ".geometry.data.MXML", with_quality=True)
    out = []
    for f, q in hits:
        out.append({"file": f, "size": os.path.getsize(f), "match": q})
    # точное совпадение полного пути всегда выше; внутри — большее лучше
    out.sort(key=lambda x: (0 if x["match"] == "exact" else 1, -x["size"]))
    return out

# --------- проект ---------


def project_state(oid):
    st = {}
    try:
        with open(PARTS_DB, "r", encoding="utf-8-sig", errors="replace") as fh:
            db = json.load(fh)
        rec = next((r for r in db if r.get("Name") == oid or
                    r.get("ObjectID", "").lstrip("^") == oid), None)
        if rec:
            st["parts_db"] = {k: rec.get(k) for k in
                              ("Name", "DisplayName", "Category", "SubCategory",
                               "ModelPath", "VariantOf")}
            mp = rec.get("ModelPath") or ""
            asset = mp.split("/")[-1].split(".")[0] if mp else ""
            if asset:
                st["mesh_asset"] = asset
                st["uasset_exists"] = os.path.isfile(
                    os.path.join(GAMEMESHES, asset + ".uasset"))
                st["obj_exists"] = os.path.isfile(
                    os.path.join(MESHSRC, asset + ".obj"))
    except Exception as e:
        st["parts_db_error"] = str(e)
    try:
        with open(PART_SLOTS, "r", encoding="utf-8-sig", errors="replace") as fh:
            slots = json.load(fh)
        if oid in slots:
            st["part_slots"] = {
                "n": len(slots[oid]),
                "slots": [{"mat": s.get("mat"), "tex": s.get("tex"),
                           "type": s.get("type", "lit")} for s in slots[oid]],
            }
    except Exception as e:
        st["part_slots_error"] = str(e)
    try:
        if "mesh_asset" in st and os.path.isfile(VERIFIED_MESHES):
            with open(VERIFIED_MESHES, "r", encoding="utf-8-sig") as fh:
                ver = json.load(fh)
            rel = "Content/NMSBaseBuilder/GameMeshes/%s.uasset" % st["mesh_asset"]
            st["mesh_verified"] = any(rel.lower() == k.replace("\\", "/").lower()
                                      for k in ver)
    except Exception:
        pass
    return st


def icon_info(oid):
    out = {}
    try:
        with open(ICON_MAP, "r", encoding="utf-8-sig", errors="replace") as fh:
            icons = json.load(fh)
        out["icon_dds"] = icons.get(oid)
    except Exception:
        pass
    png = os.path.join(ICON_PNG_DIR, oid + ".png")
    out["icon_png"] = png if os.path.isfile(png) else None
    return out

# ------------------------------------------------------------------ main


def part_id_candidates(oid, obj):
    cands = []
    if obj and obj.get("SinglePartID"):
        cands.append(obj["SinglePartID"])
    if oid.startswith("_"):
        cands.append(oid)
    m = re.match(r"^[A-Z]_(.+)$", oid)
    if m:
        cands.append("_" + m.group(1))
    cands.append("_" + oid)
    seen, out = set(), []
    for c in cands:
        if c and c not in seen:
            seen.add(c)
            out.append(c)
    return out


def lookup(oid, style=None, brief=False, use_placement=False):
    r = {"query": oid}
    obj = parse_objectstable(oid)
    r["objectstable"] = obj
    if obj and not style and obj.get("Style") and obj["Style"] != "None":
        style = obj["Style"]
    r["style_used"] = style

    part = None
    for pid in part_id_candidates(oid, obj):
        part = parse_partstable(pid)
        if part:
            break
    r["partstable"] = part
    r["legacy"] = parse_legacy(oid)

    # какая сцена главная: partstable[style] > PlacementScene
    scene_path = None
    if part and part["StyleModels"]:
        if style:
            hit = next((s for s in part["StyleModels"]
                        if s["Style"].lower() == style.lower()), None)
            scene_path = hit["Scene"] if hit else part["StyleModels"][0]["Scene"]
        else:
            scene_path = part["StyleModels"][0]["Scene"]
    elif obj and obj.get("PlacementScene"):
        scene_path = obj["PlacementScene"]

    # ЛОВУШКА S_CONTAINER0: partstable-сцена и PlacementScene бывают РАЗНЫМИ мешами
    # (container_0-ящик vs storageroom-комната). Сверять с иконкой (Правило 18)!
    if part and obj and obj.get("PlacementScene") and scene_path:
        a = re.sub(r"_placement$", "", norm_key(scene_path).split("__")[-1])
        b = re.sub(r"_placement$", "", norm_key(obj["PlacementScene"]).split("__")[-1])
        if a != b:
            r["scene_mismatch"] = {"partstable": scene_path,
                                   "placement": obj["PlacementScene"]}
            if use_placement:
                scene_path = obj["PlacementScene"]
    r["scene_path"] = scene_path

    if scene_path and not brief:
        files = find_decoded(scene_path, SCENE_DIRS, ".scene.MXML")
        if files:
            scene = parse_scene(files[0])
            r["scene"] = scene
            if scene["GEOMETRY"]:
                r["geometry"] = find_geometry(scene["GEOMETRY"])
            mats = sorted({m["MATERIAL"] for m in scene["meshes"]
                           if m["MATERIAL"]})
            r["materials"] = [parse_material(mp) for mp in mats]
        else:
            r["scene"] = {"error": "сцена не расшифрована: " + scene_path}

    # хулл: по part-ID (в autogen ключи part-ID) и по самому oid
    hulls = []
    for pid in part_id_candidates(oid, obj):
        hulls = hull_bbox(pid, style)
        if hulls:
            r["hull_part_id"] = pid
            break
    if not hulls:
        hulls = hull_bbox(oid, style)
        if hulls:
            r["hull_part_id"] = oid
    r["hulls"] = hulls

    r["icon"] = icon_info(oid)
    r["project"] = project_state(oid)
    return r


def fmt_report(r):
    L = []
    oid = r["query"]
    L.append("=" * 72)
    L.append("ПАСПОРТ ДЕТАЛИ: %s   (стиль: %s)" % (oid, r.get("style_used") or "—"))
    L.append("=" * 72)
    obj = r.get("objectstable")
    if obj:
        L.append("[objectstable / PRECACHE_FULL]")
        L.append("  Style=%s  SinglePartID=%s" % (obj["Style"], obj["SinglePartID"] or "—"))
        L.append("  PlacementScene: %s" % (obj["PlacementScene"] or "—"))
        L.append("  Меню: %s  |  ShowInBuildMenu=%s" % ("; ".join(obj["Groups"]) or "—",
                                                        obj["ShowInBuildMenu"]))
        L.append("  Палитры: colour=%s material=%s  CanChangeColour=%s CanChangeMaterial=%s"
                 % (obj["ColourPaletteGroupId"], obj["MaterialGroupId"],
                    obj["CanChangeColour"], obj["CanChangeMaterial"]))
        L.append("  CanScale=%s CanRotate3D=%s SnapRotateBlocked=%s"
                 % (obj["CanScale"], obj["CanRotate3D"], obj["SnapRotateBlocked"]))
        bb = obj["Buildable"]
        L.append("  Где строится: " + ", ".join("%s=%s" % (k.replace("BuildableOn", "").replace("Buildable", ""), v)
                                                for k, v in bb.items()))
        if obj["CompositePartObjectIDs"]:
            L.append("  КОМПОЗИТ из: " + ", ".join(obj["CompositePartObjectIDs"]))
        if obj["FamilyIDs"]:
            L.append("  Семьи: " + ", ".join(obj["FamilyIDs"]))
        if obj["HasLinkGridData"]:
            L.append("  Есть LinkGridData (электрика/розетки)")
    else:
        L.append("[objectstable] НЕТ записи _id=\"%s\"" % oid)
    if r.get("legacy"):
        L.append("[legacybasebuildingtable] запись ЕСТЬ (легаси-группа)")

    part = r.get("partstable")
    if part:
        L.append("[partstable / PRECACHE_FULL]  part-ID=%s" % part["ID"])
        for s in part["StyleModels"]:
            mark = " *" if r.get("style_used") and s["Style"].lower() == r["style_used"].lower() else ""
            L.append("  %-12s %s%s" % (s["Style"], s["Scene"], mark))
    else:
        L.append("[partstable] part-ID не найден (пробовал: %s)"
                 % ", ".join(part_id_candidates(oid, obj)))

    if r.get("scene_mismatch"):
        mm = r["scene_mismatch"]
        L.append("!! ВНИМАНИЕ: partstable и PlacementScene ведут на РАЗНЫЕ меши — сверь с иконкой (Правило 18)!")
        L.append("!!   partstable:     %s" % mm["partstable"])
        L.append("!!   PlacementScene: %s   (разобрать её: --placement)" % mm["placement"])
    L.append("[СЦЕНА] %s" % (r.get("scene_path") or "—"))
    sc = r.get("scene")
    if sc and "error" not in sc:
        L.append("  файл: %s" % sc["file"])
        L.append("  GEOMETRY: %s  (NUMLODS=%s)" % (sc["GEOMETRY"], sc["NUMLODS"]))
        lod0 = [m for m in sc["meshes"] if m["LODLEVEL"] in ("", "0")]
        L.append("  MESH-узлов: %d (LOD0: %d)" % (len(sc["meshes"]), len(lod0)))
        for m in lod0[:25]:
            L.append("    %-28s %s" % (m["Name"], m["MATERIAL"]))
        if sc["references"]:
            L.append("  СОСТАВНАЯ! REFERENCE (%d):" % len(sc["references"]))
            for rf in sc["references"][:15]:
                L.append("    %-24s -> %s" % (rf["Name"], rf["SCENEGRAPH"]))
        snap = [lc for lc in sc["locators"] if "snappoint" in (lc["Name"] or "").lower()
                or "_in_" in (lc["Name"] or "").lower() or "_out_" in (lc["Name"] or "").lower()]
        if snap:
            L.append("  Снап-локаторы (%d):" % len(snap))
            for s in snap[:20]:
                L.append("    %-28s pos=(%s, %s, %s) rotY=%s"
                         % (s["Name"], s["pos"][0], s["pos"][1], s["pos"][2], s["rotY"]))
        if sc["collisions"]:
            L.append("  Коллизии: %s" % ", ".join(
                "%s(%s)" % (c["Name"], c["TYPE"]) for c in sc["collisions"][:10]))
    elif sc:
        L.append("  !! " + sc["error"])

    geo = r.get("geometry")
    if geo:
        L.append("[ГЕОМЕТРИЯ] кандидатов: %d (первый = лучший)" % len(geo))
        for g in geo[:5]:
            L.append("    %8.1f KB  [%s]  %s" % (g["size"] / 1024.0, g["match"], g["file"]))

    mats = r.get("materials")
    if mats:
        L.append("[МАТЕРИАЛЫ] (%d)" % len(mats))
        for m in mats:
            if not m.get("decoded"):
                L.append("  !! НЕ РАСШИФРОВАН: %s" % m["game_path"])
                continue
            warn = "  (по короткому имени — возможна коллизия!)" if m.get("approx_by_name") else ""
            L.append("  %s  Class=%s%s" % (os.path.basename(m["decoded"]).replace(".material.MXML", ""),
                                           m.get("Class", ""), warn))
            if m.get("Flags"):
                L.append("    Флаги: " + " ".join(m["Flags"]))
            if m.get("gMaterialColourVec4"):
                L.append("    gMaterialColourVec4 = %s" % m["gMaterialColourVec4"])
            for s in m.get("Samplers", []):
                L.append("    %-18s sRGB=%-5s %s" % (s["Name"], s["IsSRGB"], s["Map"]))
            se = m.get("Shader")
            if se:
                L.append("    ── ЭМУЛЯЦИЯ ШЕЙДЕРА (что убершейдер сделает с пикселем; gDynamicFlags.x=0x%X) ──" % se.get("dyn_x", 0))
                L.append("      Roughness   : %s" % se.get("roughness"))
                L.append("      Metallic    : %s" % se.get("metallic"))
                L.append("      Glow        : %s" % se.get("glow"))
                L.append("      Subsurface  : %s" % se.get("subsurface"))
                L.append("      AO          : %s" % se.get("ao"))
                L.append("      Покраска    : %s" % se.get("paint"))
                tags = []
                if se.get("is_multitexture"): tags.append("мультитекстура-отделка (F55, слой=UserData байт3)")
                if se.get("is_glass"): tags.append("стекло (F30, 5-й сэмплер gRefractionMap)")
                if se.get("is_unlit"): tags.append("unlit")
                if se.get("uv2"): tags.append("2-й UV-комплект (F16/F42)")
                if tags:
                    L.append("      Особое      : " + "; ".join(tags))
                bits = se.get("active_bits") or []
                if bits:
                    L.append("      Активные биты gDynamicFlags.x:")
                    for b, d in bits:
                        L.append("        0x%-5X %s" % (b, d))

    hulls = r.get("hulls")
    if hulls:
        L.append("[ХУЛЛ MagicData / PRECACHE_FULL]  part-ID=%s" % r.get("hull_part_id", "?"))
        for h in hulls[:6]:
            L.append("  %-12s size=(%.2f x %.2f x %.2f) м  min=(%.2f,%.2f,%.2f) max=(%.2f,%.2f,%.2f)  vtx=%d"
                     % (h["Style"] or "None",
                        h["size"][0], h["size"][1], h["size"][2],
                        h["min"][0], h["min"][1], h["min"][2],
                        h["max"][0], h["max"][1], h["max"][2], h["nverts"]))

    ic = r.get("icon", {})
    if ic.get("icon_dds") or ic.get("icon_png"):
        L.append("[ИКОНКА / Правило 18]")
        if ic.get("icon_dds"):
            L.append("  dds-имя: %s" % ic["icon_dds"])
        if ic.get("icon_png"):
            L.append("  эталон PNG: %s" % ic["icon_png"])

    pr = r.get("project", {})
    if pr:
        L.append("[ПРОЕКТ NMS_BuilderApp]")
        pdb = pr.get("parts_db")
        if pdb:
            L.append("  parts_db: %s | %s / %s" % (pdb.get("DisplayName"),
                                                   pdb.get("Category"), pdb.get("SubCategory")))
            L.append("  ModelPath: %s" % pdb.get("ModelPath"))
            L.append("  uasset: %s   OBJ в MeshSrc: %s   verified: %s"
                     % ("ЕСТЬ" if pr.get("uasset_exists") else "НЕТ",
                        "ЕСТЬ" if pr.get("obj_exists") else "НЕТ",
                        pr.get("mesh_verified", "—")))
        else:
            L.append("  в nms_parts_db.json записи НЕТ")
        ps = pr.get("part_slots")
        if ps:
            L.append("  part_slots: %d слотов:" % ps["n"])
            for s in ps["slots"][:20]:
                L.append("    %-26s %-11s %s" % (s["mat"], "[%s]" % s["type"], s["tex"]))
        else:
            L.append("  part_slots: записи НЕТ")
    return "\n".join(L)


def main():
    ap = argparse.ArgumentParser(description="Паспорт детали NMS по ObjectID (1:1 из игры)")
    ap.add_argument("object_id", help="ObjectID (можно с ^): TELEPORTER, _WALLB, W_WALL...")
    ap.add_argument("--style", help="стиль (Timber/Stone/Wood/...); по умолчанию из objectstable")
    ap.add_argument("--json", action="store_true", help="вывод JSON вместо отчёта")
    ap.add_argument("--brief", action="store_true", help="без разбора сцены/материалов")
    ap.add_argument("--placement", action="store_true",
                    help="при расхождении сцен разобрать PlacementScene, а не partstable")
    args = ap.parse_args()

    oid = args.object_id.strip().lstrip("^").upper()
    r = lookup(oid, style=args.style, brief=args.brief, use_placement=args.placement)
    if args.json:
        print(json.dumps(r, ensure_ascii=False, indent=1, default=str))
    else:
        print(fmt_report(r))


if __name__ == "__main__":
    main()
