# -*- coding: utf-8 -*-
"""
nms_indexer.py — «компилятор связей»: указываешь папку PCBANKS игры, программа САМА
достаёт из паков таблицы, расшифровывает их MBINCompiler'ом, проходит цепочку связей
для ВСЕХ деталей стройки и выдаёт готовую базу + отчёт.

Использование:
    python nms_indexer.py "D:\\...\\GAMEDATA\\PCBANKS" --out "C:\\Users\\User\\Desktop\\NMS_INDEX"

Этапы (всё 1:1 из указанных паков, ничего из старых дампов):
  0. Скан паков: оглавление каждого .pak -> pak_manifest.json (путь -> пак).
     При дублях путь берётся из pak'а с 'precache' в имени (урок TELEPORTER 01.07.2026).
  1. Извлечение и декод 4 таблиц: objectstable, partstable, legacytable, autogen (хуллы).
  2. Полный разбор таблиц: все GcBaseBuildingEntry + все part-ID + все хуллы.
  3. Сцены: извлечь+декодировать все сцены деталей (стили + placement), разобрать
     (геометрия, MESH LOD0 + материалы, снап-локаторы, REFERENCE-композиты, коллизии),
     рекурсивно по REFERENCE (глубина --deep, по умолчанию 2).
  4. Материалы: извлечь+декодировать все .MATERIAL, разобрать (класс, флаги _F,
     цвет, сэмплеры-текстуры) + проверить наличие текстур в паках.
  5. Сборка parts_links.json (детали + общие словари сцен/материалов) + REPORT.txt.

Повторный запуск инкрементален: уже извлечённое/расшифрованное не переделывается.

Флаги: --limit N (первые N деталей — быстрый тест), --tables-only (только этапы 0-2),
       --deep N, --rescan (пересобрать оглавление паков), --mbin <путь к MBINCompiler.exe>.
"""
import argparse
import json
import os
import re
import struct
import subprocess
import sys
import xml.etree.ElementTree as ET
from functools import lru_cache

try:
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
except Exception:
    pass

DEF_MBIN = r"C:\Users\User\Desktop\MBINCompiler\MBINCompiler.exe"
CHUNK = 0x10000

TABLE_PATHS = [
    "metadata/reality/tables/basebuildingobjectstable.mbin",
    "metadata/reality/tables/basebuildingpartstable.mbin",
    "metadata/reality/tables/legacybasebuildingtable.mbin",
    "metadata/reality/tables/basebuildingautogeneratedpartsdata.mbin",
    "metadata/reality/tables/nms_basepartproducts.mbin",   # иконки деталей (Icon у продукта)
    "metadata/reality/tables/nms_reality_gcproducttable.mbin",  # запасной источник иконок
]

# ------------------------------------------------------------------ HGPAK

class HGPak(object):
    """Читальщик HGPAK (NMS 5.5+): манифест имён + извлечение файла по индексу.
    По мотивам 10_TOOLS/hgpak_extract_zstdmod.py (проверенный формат)."""

    def __init__(self, path):
        import zstandard
        self.path = path
        self.f = open(path, "rb")
        assert self.f.read(5) == b"HGPAK", "не HGPAK: " + path
        self.f.seek(8)
        (self.ver, self.n_files, self.n_chunks, self.comp,
         self.data_off) = struct.unpack("<QQQ?7xQ", self.f.read(0x28))
        self.finfo = []
        for _ in range(self.n_files):
            _h, off, size = struct.unpack("<16s2Q", self.f.read(0x20))
            self.finfo.append((off, size))
        if self.comp:
            sizes = struct.unpack("<%dQ" % self.n_chunks, self.f.read(8 * self.n_chunks))
            self.sizes = sizes
            self.offs = []
            cur = self.data_off
            for s in sizes:
                self.offs.append(cur)
                cur += ((s + 0xF) // 0x10) * 0x10
        else:
            # несжатый пак (напр. NMSARC.audio.pak): таблицы чанков НЕТ,
            # данные лежат сплошняком сразу после таблицы файлов (data_off)
            self.sizes = None
        self._dctx = zstandard.ZstdDecompressor()
        self._chunk = lru_cache(maxsize=64)(self._chunk_raw)

    def _chunk_raw(self, i):
        self.f.seek(self.offs[i])
        data = self.f.read(self.sizes[i])
        if not self.comp:
            return data
        try:
            return self._dctx.decompress(data, max_output_size=CHUNK)
        except Exception:
            if len(data) == CHUNK:
                return data  # несжатый блок
            raise

    def read_span(self, off, size):
        if not self.comp:
            self.f.seek(self.data_off + off)
            return self.f.read(size)
        out = bytearray()
        c0, c1 = off // CHUNK, (off + size - 1) // CHUNK
        for ci in range(c0, c1 + 1):
            d = self._chunk(ci)
            a = off - ci * CHUNK if ci == c0 else 0
            b = off + size - ci * CHUNK if ci == c1 else len(d)
            out += d[a:b]
        return bytes(out)

    def names(self):
        man = self.read_span(0, self.finfo[0][1])
        return [n.decode() for n in man.rstrip(b"\r\n").split(b"\r\n")]

    def extract(self, index):
        off, size = self.finfo[index + 1]  # +1: файл 0 = манифест
        return self.read_span(off - self.data_off, size)

    def close(self):
        self.f.close()


# ------------------------------------------------------------------ этап 0: манифест

def norm(p):
    return p.replace("\\", "/").lower()


def _long(p):
    """Windows: префикс \\\\?\\ снимает лимит пути 260 символов (глубокие папки)."""
    if os.name == "nt":
        p2 = os.path.abspath(p)
        if not p2.startswith("\\\\?\\"):
            return "\\\\?\\" + p2
    return p


def build_manifest(pcbanks, out_dir, rescan=False):
    """путь_в_игре(lower) -> {pak, index, name} (+ dups счётчик)."""
    mf_path = os.path.join(out_dir, "pak_manifest.json")
    if os.path.isfile(mf_path) and not rescan:
        with open(mf_path, "r", encoding="utf-8") as fh:
            print("[0] оглавление паков: из кэша pak_manifest.json")
            return json.load(fh)
    paks = sorted(f for f in os.listdir(pcbanks) if f.lower().endswith(".pak"))
    if not paks:
        sys.exit("В папке нет .pak файлов: " + pcbanks)
    manifest, dups = {}, 0
    for i, pk in enumerate(paks):
        full = os.path.join(pcbanks, pk)
        try:
            pak = HGPak(full)
            names = pak.names()
            pak.close()
        except Exception as e:
            print("  ! пропуск %s: %s" % (pk, e))
            continue
        prec = "precache" in pk.lower()
        for idx, nm in enumerate(names):
            key = norm(nm)
            if key in manifest:
                dups += 1
                # приоритет pak'у с precache в имени — там актуальные таблицы
                if not prec:
                    continue
            manifest[key] = {"pak": pk, "index": idx, "name": nm}
        print("  [%d/%d] %-40s файлов: %d" % (i + 1, len(paks), pk, len(names)))
    with open(mf_path, "w", encoding="utf-8") as fh:
        json.dump(manifest, fh, ensure_ascii=False)
    print("[0] всего путей: %d (перекрытий: %d) -> pak_manifest.json" % (len(manifest), dups))
    return manifest


# ------------------------------------------------------------------ извлечение+декод

_open_paks = {}

def get_pak(pcbanks, pk):
    if pk not in _open_paks:
        _open_paks[pk] = HGPak(os.path.join(pcbanks, pk))
    return _open_paks[pk]


def extract_files(pcbanks, manifest, game_paths, raw_dir):
    """Извлекает список игровых путей в raw_dir (со структурой). Возвращает
    {game_path_lower: локальный_путь | None}. Уже извлечённое не трогает."""
    out = {}
    for gp in game_paths:
        key = norm(gp)
        rec = manifest.get(key)
        if rec is None and not key.endswith(".pc"):
            rec = manifest.get(key + ".pc")   # геометрия в паках = .MBIN.PC
            key = key + ".pc" if rec else key
        if rec is None:
            out[norm(gp)] = None
            continue
        dst = os.path.join(raw_dir, key.replace("/", os.sep))
        if not os.path.isfile(_long(dst)):
            os.makedirs(_long(os.path.dirname(dst)), exist_ok=True)
            data = get_pak(pcbanks, rec["pak"]).extract(rec["index"])
            with open(_long(dst), "wb") as fh:
                fh.write(data)
        out[norm(gp)] = dst
    return out


def decode_files(mbin_exe, files):
    """MBINCompiler -y -q пачками; пропускает то, у чего .MXML уже есть.
    Возвращает {mbin_путь: mxml_путь | None}."""
    res, todo = {}, []
    for f in files:
        if f is None:
            continue
        mx = re.sub(r"\.mbin(\.pc)?$", ".MXML", f, flags=re.I)
        res[f] = mx if os.path.isfile(mx) else None
        if res[f] is None:
            todo.append(f)
    BATCH = 40
    for i in range(0, len(todo), BATCH):
        batch = todo[i:i + BATCH]
        subprocess.run([mbin_exe, "-y", "-q"] + batch,
                       capture_output=True, timeout=600)
        if len(todo) > BATCH:
            print("    декод: %d/%d" % (min(i + BATCH, len(todo)), len(todo)))
    for f in todo:
        mx = re.sub(r"\.mbin(\.pc)?$", ".MXML", f, flags=re.I)
        res[f] = mx if os.path.isfile(mx) else None
    return res


# ------------------------------------------------------------------ разбор таблиц

def prop_val(text, name, default=""):
    m = re.search(r'<Property name="%s" value="([^"]*)"' % re.escape(name), text)
    return m.group(1) if m else default


def prop_vals(text, name):
    return re.findall(r'<Property name="%s" value="([^"]*)"' % re.escape(name), text)


def iter_entries(path, open_prefix):
    """Стриминг записей таблицы (открытие на open_prefix, закрытие тем же отступом)."""
    close_line = open_prefix.split("<")[0] + "</Property>"
    entry, inside = [], False
    with open(path, "r", encoding="utf-8", errors="replace") as fh:
        for line in fh:
            ls = line.rstrip("\n")
            if ls.startswith(open_prefix):
                entry, inside = [ls], True
                continue
            if inside:
                entry.append(ls)
                if ls == close_line:
                    yield "\n".join(entry)
                    inside = False


def parse_objectstable_full(mxml):
    objs = {}
    for e in iter_entries(mxml, '\t\t<Property name="Objects"'):
        oid = prop_val(e, "ID")
        if not oid:
            continue
        style_m = re.search(r'name="Style" value="GcBaseBuildingPartStyle">\s*\n\s*'
                            r'<Property name="Style" value="([^"]*)"', e)
        groups = re.findall(r'<Property name="Group" value="([^"]*)" />\s*\n\s*'
                            r'<Property name="SubGroupName" value="([^"]*)"', e)
        comp = re.search(r'<Property name="CompositePartObjectIDs">(.*?)^\t{3}</Property>',
                         e, re.S | re.M)
        fam = re.search(r'<Property name="FamilyIDs">(.*?)^\t{3}</Property>', e, re.S | re.M)
        objs[oid] = {
            "Style": style_m.group(1) if style_m else "",
            "PlacementScene": prop_val(e, "Filename"),
            "SinglePartID": prop_val(e, "SinglePartID"),
            "Groups": ["%s/%s" % g for g in groups],
            "ShowInBuildMenu": prop_val(e, "ShowInBuildMenu") == "true",
            "IsPlaceable": prop_val(e, "IsPlaceable") == "true",
            "ColourPaletteGroupId": prop_val(e, "ColourPaletteGroupId"),
            "MaterialGroupId": prop_val(e, "MaterialGroupId"),
            "CanChangeColour": prop_val(e, "CanChangeColour") == "true",
            "CanChangeMaterial": prop_val(e, "CanChangeMaterial") == "true",
            "CanScale": prop_val(e, "CanScale") == "true",
            "CanRotate3D": prop_val(e, "CanRotate3D") == "true",
            "SnapRotateBlocked": prop_val(e, "SnapRotateBlocked") == "true",
            "Composites": prop_vals(comp.group(1), "CompositePartObjectIDs") if comp else [],
            "Families": prop_vals(fam.group(1), "FamilyIDs") if fam else [],
            "HasLinkGridData": 'name="LinkGridData"' in e,
            "IconOverrideProductID": prop_val(e, "IconOverrideProductID"),
        }
    return objs


def parse_product_icons(mxml):
    """nms_basepartproducts: ID продукта (= ID детали) -> путь DDS-иконки."""
    icons = {}
    for e in iter_entries(mxml, '\t\t<Property '):
        pid = prop_val(e, "ID")
        m = re.search(r'name="Icon" value="TkTextureResource">\s*\n\s*'
                      r'<Property name="Filename" value="([^"]*)"', e)
        if pid and m and m.group(1):
            icons[pid] = m.group(1)
    return icons


def parse_partstable_full(mxml):
    parts = {}
    # свежий декод 6.34 открывает записи как name="Parts"; старые дампы — name="Table"
    opener = '\t\t<Property name="Parts"'
    with open(mxml, "r", encoding="utf-8", errors="replace") as fh:
        head = fh.read(4096)
    if 'name="Parts"' not in head:
        opener = '\t\t<Property name="Table"'
    for e in iter_entries(mxml, opener):
        pid = prop_val(e, "ID")
        if not pid:
            continue
        styles = re.findall(
            r'<Property name="Style" value="([^"]*)" />\s*\n\s*</Property>\s*\n\s*'
            r'<Property name="Model" value="TkModelResource">\s*\n\s*'
            r'<Property name="Filename" value="([^"]*)"', e)
        parts[pid] = {s: f for s, f in styles}
    return parts


def parse_autogen_full(mxml):
    hulls = {}
    for e in iter_entries(mxml, '\t\t<Property name="PartsData"'):
        pid = prop_val(e, "PartID")
        if not pid:
            continue
        style_m = re.search(r'name="Style" value="GcBaseBuildingPartStyle">\s*\n\s*'
                            r'<Property name="Style" value="([^"]*)"', e)
        st = style_m.group(1) if style_m else "None"
        xs = [float(v) for v in prop_vals(e, "X")]
        ys = [float(v) for v in prop_vals(e, "Y")]
        zs = [float(v) for v in prop_vals(e, "Z")]
        if not xs:
            continue
        hulls.setdefault(pid, {})[st] = {
            "min": [round(min(xs), 4), round(min(ys), 4), round(min(zs), 4)],
            "max": [round(max(xs), 4), round(max(ys), 4), round(max(zs), 4)],
            "size": [round(max(xs) - min(xs), 4), round(max(ys) - min(ys), 4),
                     round(max(zs) - min(zs), 4)],
        }
    return hulls


def parse_legacy_ids(mxml):
    ids = set()
    for e in iter_entries(mxml, '\t\t<Property name="Objects"'):
        oid = prop_val(e, "ID")
        if oid:
            ids.add(oid)
    return ids


# ------------------------------------------------------------------ сцены/материалы

def et_props(el):
    d = {}
    for c in el:
        d.setdefault(c.get("name"), []).append(c)
    return d


def node_info(el):
    p = et_props(el)
    g = lambda k: (p.get(k, [None])[0].get("value") if p.get(k, [None])[0] is not None else "")
    info = {"Name": g("Name"), "Type": g("Type"), "Attrs": {}, "Transform": {}, "Children": []}
    tr = p.get("Transform", [None])[0]
    if tr is not None:
        for c in tr:
            info["Transform"][c.get("name")] = c.get("value")
    attrs = p.get("Attributes", [None])[0]
    if attrs is not None:
        for a in attrs:
            ap = et_props(a)
            an, av = ap.get("Name", [None])[0], ap.get("Value", [None])[0]
            if an is not None and av is not None:
                info["Attrs"][an.get("value")] = av.get("value")
    ch = p.get("Children", [None])[0]
    if ch is not None:
        for c in ch:
            info["Children"].append(node_info(c))
    return info


def walk(n, out=None):
    if out is None:
        out = []
    out.append(n)
    for c in n["Children"]:
        walk(c, out)
    return out


def parse_scene_mxml(mxml):
    try:
        root = node_info(ET.parse(mxml).getroot())
    except ET.ParseError as e:
        return {"error": "parse: %s" % e}
    nodes = walk(root)
    meshes, snap, refs, colls = [], [], [], []
    for n in nodes:
        t = n["Type"]
        if t == "MESH" and n["Attrs"].get("LODLEVEL", "0") == "0":
            meshes.append({"name": n["Name"], "material": n["Attrs"].get("MATERIAL", "")})
        elif t == "LOCATOR":
            nm = (n["Name"] or "").lower()
            if "snappoint" in nm or "_in_" in nm or "_out_" in nm:
                tr = n["Transform"]
                snap.append({"name": n["Name"],
                             "pos": [tr.get("TransX"), tr.get("TransY"), tr.get("TransZ")],
                             "rotY": tr.get("RotY")})
        elif t == "REFERENCE":
            refs.append({"name": n["Name"], "scene": n["Attrs"].get("SCENEGRAPH", "")})
        elif t == "COLLISION":
            colls.append({"name": n["Name"], "type": n["Attrs"].get("TYPE", "")})
    return {"geometry": root["Attrs"].get("GEOMETRY", ""),
            "numlods": root["Attrs"].get("NUMLODS", ""),
            "meshes": meshes, "snap": snap, "references": refs, "collisions": colls}


def parse_material_mxml(mxml):
    try:
        tree = ET.parse(mxml)
    except ET.ParseError as e:
        return {"error": "parse: %s" % e}
    flags, samplers, mclass, colour = [], [], "", None

    def rec(el):
        nonlocal mclass, colour
        name = el.get("name")
        if name == "MaterialFlag":
            flags.append(el.get("value"))
        elif name == "MaterialClass":
            mclass = el.get("value")
        elif name == "Samplers" and el.get("value") == "TkMaterialSampler":
            p = et_props(el)
            g = lambda k: (p.get(k, [None])[0].get("value") if p.get(k, [None])[0] is not None else "")
            samplers.append({"name": g("Name"), "map": g("Map"), "srgb": g("IsSRGB")})
        elif name == "Uniforms_Float" and el.get("value") == "TkMaterialUniform_Float":
            p = et_props(el)
            un = p.get("Name", [None])[0]
            if un is not None and un.get("value") == "gMaterialColourVec4":
                vals = re.findall(r'value="([-\d.]+)"', ET.tostring(el, encoding="unicode"))
                colour = vals[1:5] if len(vals) > 4 else vals
        for c in el:
            rec(c)

    rec(tree.getroot())
    return {"class": mclass, "flags": flags, "colour": colour, "samplers": samplers}


# ------------------------------------------------------------------ main

def part_id_for(oid, obj):
    if obj.get("SinglePartID"):
        return obj["SinglePartID"]
    m = re.match(r"^[A-Z]_(.+)$", oid)
    if m:
        return "_" + m.group(1)
    return "_" + oid


def main():
    ap = argparse.ArgumentParser(description="Индексатор связей деталей NMS из PCBANKS")
    ap.add_argument("pcbanks", help="папка GAMEDATA\\PCBANKS с .pak файлами")
    ap.add_argument("--out", default=r"C:\Users\User\Desktop\NMS_INDEX",
                    help="папка результата (по умолчанию Desktop\\NMS_INDEX)")
    ap.add_argument("--mbin", default=DEF_MBIN, help="путь к MBINCompiler.exe")
    ap.add_argument("--limit", type=int, default=0, help="только первые N деталей (тест)")
    ap.add_argument("--tables-only", action="store_true", help="только таблицы, без сцен")
    ap.add_argument("--deep", type=int, default=2, help="глубина рекурсии REFERENCE (2)")
    ap.add_argument("--rescan", action="store_true", help="пересобрать оглавление паков")
    args = ap.parse_args()

    if not os.path.isdir(args.pcbanks):
        sys.exit("Нет папки: " + args.pcbanks)
    if not os.path.isfile(args.mbin):
        sys.exit("Нет MBINCompiler.exe: " + args.mbin)
    os.makedirs(args.out, exist_ok=True)
    raw = os.path.join(args.out, "raw")

    # 0-1: манифест + таблицы
    manifest = build_manifest(args.pcbanks, args.out, rescan=args.rescan)
    print("[1] извлекаю и декодирую таблицы...")
    loc = extract_files(args.pcbanks, manifest, TABLE_PATHS, raw)
    missing = [k for k, v in loc.items() if v is None]
    if missing:
        sys.exit("В паках не найдены таблицы: %s" % ", ".join(missing))
    dec = decode_files(args.mbin, list(loc.values()))
    mx = {os.path.basename(k): v for k, v in dec.items()}
    for k, v in dec.items():
        if v is None:
            sys.exit("Не декодировалась таблица: %s (см. MBINCompiler.log)" % k)

    # 2: полный разбор
    print("[2] разбираю таблицы...")
    objs = parse_objectstable_full(mx["basebuildingobjectstable.mbin"])
    parts = parse_partstable_full(mx["basebuildingpartstable.mbin"])
    hulls = parse_autogen_full(mx["basebuildingautogeneratedpartsdata.mbin"])
    legacy = parse_legacy_ids(mx["legacybasebuildingtable.mbin"])
    print("    объектов: %d, part-ID: %d, хуллов: %d, легаси: %d"
          % (len(objs), len(parts), len(hulls), len(legacy)))

    oids = sorted(objs.keys())
    if args.limit:
        oids = oids[:args.limit]

    db = {"_source": {"pcbanks": os.path.abspath(args.pcbanks)},
          "parts": {}, "scenes": {}, "materials": {}}

    if not args.tables_only:
        # 3: сцены (стили выбранной детали + placement) + рекурсия REFERENCE
        want_scenes = set()
        for oid in oids:
            o = objs[oid]
            pid = part_id_for(oid, o)
            for sc in parts.get(pid, {}).values():
                want_scenes.add(sc)
            if o["PlacementScene"]:
                want_scenes.add(o["PlacementScene"])
        scene_info = {}
        depth = 0
        while want_scenes and depth <= args.deep:
            todo = sorted(s for s in want_scenes if norm(s) not in scene_info)
            if not todo:
                break
            print("[3] сцены, волна %d: %d шт..." % (depth, len(todo)))
            loc = extract_files(args.pcbanks, manifest, todo, raw)
            dec = decode_files(args.mbin, [v for v in loc.values() if v])
            nxt = set()
            for gp in todo:
                lf = loc.get(norm(gp))
                mxf = dec.get(lf) if lf else None
                if mxf is None:
                    scene_info[norm(gp)] = {"error": "нет в паках" if lf is None else "не декодировалась"}
                    continue
                si = parse_scene_mxml(mxf)
                scene_info[norm(gp)] = si
                for rf in si.get("references", []):
                    if rf["scene"]:
                        nxt.add(rf["scene"])
            want_scenes = nxt
            depth += 1

        # 4: материалы
        want_mats = set()
        for si in scene_info.values():
            for m in si.get("meshes", []):
                if m["material"]:
                    want_mats.add(m["material"])
        print("[4] материалы: %d шт..." % len(want_mats))
        loc = extract_files(args.pcbanks, manifest, sorted(want_mats), raw)
        dec = decode_files(args.mbin, [v for v in loc.values() if v])
        for gp in want_mats:
            lf = loc.get(norm(gp))
            mxf = dec.get(lf) if lf else None
            if mxf is None:
                db["materials"][norm(gp)] = {"error": "нет в паках" if lf is None else "не декодировался"}
                continue
            mi = parse_material_mxml(mxf)
            for s in mi.get("samplers", []):
                s["in_pak"] = norm(s["map"]) in manifest
            db["materials"][norm(gp)] = mi

        # наличие геометрии в паках
        for k, si in scene_info.items():
            g = si.get("geometry")
            if g:
                gk = norm(g)
                si["geometry_in_pak"] = (gk in manifest) or (gk + ".pc" in manifest)
        db["scenes"] = scene_info

    # иконки: продукт с тем же ID (или IconOverrideProductID) -> DDS из пака -> PNG
    print("[иконки] разбираю таблицы продуктов и достаю иконки...")
    icons_map = parse_product_icons(mx["nms_reality_gcproducttable.mbin"])
    icons_map.update(parse_product_icons(mx["nms_basepartproducts.mbin"]))  # basepart главнее
    icon_dir = os.path.join(args.out, "icons")
    os.makedirs(icon_dir, exist_ok=True)
    try:
        from PIL import Image
        have_pil = True
    except ImportError:
        have_pil = False
        print("  !! Pillow не установлен — DDS не конвертируются в PNG (pip install pillow)")
    icon_of = {}
    n_new = n_have = n_noicon = n_fail = 0
    for k, oid in enumerate(oids):
        o = objs[oid]
        prod = o.get("IconOverrideProductID") or oid
        dds = icons_map.get(prod)
        if not dds:
            n_noicon += 1
            continue
        png = os.path.join(icon_dir, oid + ".png")
        if os.path.isfile(png):
            n_have += 1
        elif have_pil:
            loc = extract_files(args.pcbanks, manifest, [dds], raw)
            lf = loc.get(norm(dds))
            if lf is None:
                n_fail += 1
                continue
            try:
                Image.open(lf).convert("RGBA").save(png)
                n_new += 1
            except Exception as e:
                n_fail += 1
                print("  !! иконка %s: %s" % (oid, e))
                continue
        else:
            continue
        icon_of[oid] = {"dds": dds, "png": png}
        if (n_new + n_have) % 400 == 0:
            print("    иконки: %d/%d" % (k + 1, len(oids)))
    print("  иконок готово: %d (новых %d), без иконки в таблице: %d, ошибок: %d"
          % (n_new + n_have, n_new, n_noicon, n_fail))

    # 5: сборка per-part
    print("[5] собираю базу деталей...")
    n_mismatch = 0
    for oid in oids:
        o = objs[oid]
        pid = part_id_for(oid, o)
        styles = parts.get(pid, {})
        style = o["Style"] if o["Style"] not in ("", "None") else None
        scene = None
        if styles:
            scene = styles.get(style) or next(iter(styles.values()))
        elif o["PlacementScene"]:
            scene = o["PlacementScene"]
        mismatch = None
        if styles and o["PlacementScene"] and scene:
            a = re.sub(r"_placement$", "", norm(scene).split("/")[-1].replace(".scene.mbin", ""))
            b = re.sub(r"_placement$", "", norm(o["PlacementScene"]).split("/")[-1].replace(".scene.mbin", ""))
            if a != b:
                mismatch = o["PlacementScene"]
                n_mismatch += 1
        rec = {"object": o, "part_id": pid, "styles": styles, "scene": scene,
               "placement_differs": mismatch,
               "hulls": hulls.get(pid) or hulls.get(oid),
               "legacy": oid in legacy,
               "icon": icon_of.get(oid)}
        if not args.tables_only and scene:
            si = db["scenes"].get(norm(scene), {})
            rec["scene_materials"] = sorted({m["material"] for m in si.get("meshes", [])
                                             if m.get("material")})
        db["parts"][oid] = rec

    # НЕ затирать прошлый полный результат частичным (--tables-only / --limit):
    # старая база подмешивается, новые данные поверх старых
    out_json = os.path.join(args.out, "parts_links.json")
    if os.path.isfile(out_json):
        try:
            with open(out_json, "r", encoding="utf-8") as fh:
                old = json.load(fh)
        except Exception:
            old = {}
        old_parts = old.get("parts") or {}
        for k, v in db["parts"].items():
            ov = old_parts.get(k)
            if ov and "scene_materials" in ov and "scene_materials" not in v:
                v["scene_materials"] = ov["scene_materials"]
        merged = old_parts
        merged.update(db["parts"])
        db["parts"] = merged
        for sect in ("scenes", "materials"):
            m = old.get(sect) or {}
            m.update(db.get(sect) or {})
            db[sect] = m
    with open(out_json, "w", encoding="utf-8") as fh:
        json.dump(db, fh, ensure_ascii=False, indent=1)

    # 6: отчёт
    rep = []
    rep.append("ОТЧЁТ ИНДЕКСАЦИИ PCBANKS: %s" % os.path.abspath(args.pcbanks))
    rep.append("Деталей (GcBaseBuildingEntry): %d%s"
               % (len(oids), "  (ограничено --limit)" if args.limit else ""))
    rep.append("part-ID в partstable: %d;  хуллов: %d;  легаси-записей: %d"
               % (len(parts), len(hulls), len(legacy)))
    if not args.tables_only:
        ok = sum(1 for s in db["scenes"].values() if "error" not in s)
        bad = [k for k, s in db["scenes"].items() if "error" in s]
        rep.append("Сцен разобрано: %d;  проблемных: %d" % (ok, len(bad)))
        for b in bad[:20]:
            rep.append("  !! сцена: %s  (%s)" % (b, db["scenes"][b]["error"]))
        mok = sum(1 for m in db["materials"].values() if "error" not in m)
        mbad = [k for k, m in db["materials"].items() if "error" in m]
        rep.append("Материалов разобрано: %d;  проблемных: %d" % (mok, len(mbad)))
        for b in mbad[:20]:
            rep.append("  !! материал: %s" % b)
        nogeo = [k for k, s in db["scenes"].items()
                 if "error" not in s and s.get("geometry") and not s.get("geometry_in_pak")]
        rep.append("Сцен с геометрией, которой НЕТ в паках: %d" % len(nogeo))
        ntex = sum(1 for m in db["materials"].values()
                   for s in m.get("samplers", []) if not s.get("in_pak"))
        rep.append("Текстур-ссылок, которых НЕТ в паках: %d" % ntex)
    rep.append("Иконок PNG в %s: %d (без иконки в таблице продуктов: %d)"
               % (icon_dir, len(icon_of), n_noicon))
    rep.append("Деталей, где partstable и PlacementScene ведут на РАЗНЫЕ меши: %d "
               "(поле placement_differs — сверять с иконкой, Правило 18)" % n_mismatch)
    rep.append("")
    rep.append("Результат: %s" % out_json)
    report = "\n".join(rep)
    with open(os.path.join(args.out, "REPORT.txt"), "w", encoding="utf-8") as fh:
        fh.write(report + "\n")
    print()
    print(report)
    for p in _open_paks.values():
        p.close()


if __name__ == "__main__":
    main()
